[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo_pgsql",
  "php82Extensions.pgsql",
  "php82Extensions.mbstring",
  "php82Extensions.openssl",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "php82Extensions.curl",
  "php82Extensions.fileinfo"
]
